project:
  type: book
  output-dir: _book

book:
  title: "BM329 Workshop A: Microbial Identification"
  reader-mode: true
  
  author: "Leighton Pritchard"
  date: "1/25/2024"
  
  cover-image: sipbs_compbio_800.png
  favicon: icon_32.png
  
  page-footer:
    left: |
      These BM211 workshops were written by Leighton Pritchard and Morgan Feeney.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.

  chapters:
    - index.qmd
    - intro.qmd
    - data.qmd
    - 16s.qmd
    - mlst.qmd
    - whole_genome.qmd
    - lpsn.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    author-meta: "Leighton Pritchard"
  pdf:
    documentclass: scrreprt



