# Preface to the {{< var ay >}} BM329 Block A workshop {.unnumbered}

Welcome to the BM329 (Biomedical Microbiology) Block A Microbial Identification workshop for {{< var ay >}}.

This year is the first presentation of this workshop material, and we would be very grateful to hear feedback [by email](mailto:{{< var admin.email >}}) or through the [GitHub repository Issues page]({{< var github.issues >}}).

## Overview

The workshop asks you to carry out common microbial identification analyses for a sequenced bacterial isolate, to determine its likely identity. You will be using online bioinformatics services to do this.

::: { .callout-warning title="Important Note"}
There is new material in this workshop that is not covered in lectures, and this material is examinable. Please take care to read the text in the expandable callout boxes, as well as that for the workshop, to be sure you have understood the topic and obtain full value from the exercise.

The workshop material will remain live online for the duration of BM329, and you can revisit it whenever you wish, for practice or revision.
:::

**You should be able to complete this workshop in under two hours.**

## Learning Objectives

By the end of this workshop, students will be able to:

- Obtain an identification for bacterial isolate from its 16S sequence, using public bioinformatics 16S sequence-matching services
- Obtain an identification for a bacterial isolate from its assembled draft genome sequence, using a range of techniques, _via_ public bioinformatics services
- Interpret sequence-based bacterial taxonomy assignments in the context of [LPSN (the List of Prokaryotic names with Standing in Nomenclature)](https://www.bacterio.net/), the arbiter of bacterial nomenclature
- Compare, and make an informed judgement between, alternative taxonomic assignments for the same isolate made using different computational approaches and databases.

## Assessment

This workshop activity itself is not formally assessed although, as noted, all the material it contains is examinable. There is a formative assessment in the form of short answer questions [on MyPlace](https://classes.myplace.strath.ac.uk/course/view.php?id=21635), which you should complete as part of the workshop.